baseURL = 'https://dcgsaar.de/'
defaultContentLanguage = 'de'
defaultContentLanguageInSubdir = true
theme = 'dcg-theme'

[languages]
  [languages.de]
    languageName = 'Deutsch'
    languageCode = 'de'
    title = 'DCG Saar'
    weight = 1
    contentDir = 'content/de'
    [languages.de.permalinks]
        categories = '/kategorien/:slug/'
    
  [languages.zh]
    languageName = '中文'
    languageCode = 'zh-cn'
    title = 'DCG萨尔'
    weight = 2
    contentDir = 'content/zh'
   [languages.zh.permalinks]
        categories = '/分类/:slug/'

[permalinks]
  posts = '/:sections/:slug/'
  events = '/:sections/:slug/'
  pages = '/:slug/'

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      autoHeadingIDType = 'github'
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  tag = "tags"
  category = "categories"
  year = "years"
  month = "months"

[params]
  showLanguageSwitcher = true

[languages.de.params]
  languageSwitcherText = "语言"
  
[languages.zh.params]
  languageSwitcherText = "Sprache"
